#!/bin/bash
sudo add-apt-repository ppa:ozcanesen/terra-terminal
sudo apt-get update
sudo apt-get install git git-gui vim build-essential cmake terra

#MXE Cross Compiling #http://mxe.cc/
sudo apt-get install autoconf automake bash bison bzip2 cmake flex gettext git g++ intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config scons sed unzip wget xz-utils
sudo apt-get install g++-multilib libc6-dev-i386
sudo mkdir -p /opt/dev/
cd /opt/dev
sudo git clone https://github.com/mxe/mxe.git
cd mxe
#sudo make gcc mingw-w64 boost opencv qt5 qwt

#Adding boost:
#Move to /opt/dev/boost/boost_version
#./bootstrap.sh gcc
#./b2 install --prefix=..toolset=gcc variant=release link=static threading=multi runtime-link=static
