#!/bin/bash

sudo add-apt-repository ppa:chris-lea/node.js #node.js
sudo apt-get update
sudo apt-get install 
# Server
#sudo apt-get install apache2 mysql-server mysql-client php5 libapache2-mod-php5 php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl php5-xcache phpmyadmin sqlite3 webmin

#Eclipse
#http://download.aptana.com/studio3/plugin/install
